# Generated by Django 6.0.4 on 2026-04-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сметы')),
                ('file', models.FileField(upload_to='estimates/', verbose_name='Файл .gge')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processing', 'В обработке'), ('checked', 'Проверена'), ('error', 'Ошибка')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Смета',
                'verbose_name_plural': 'Сметы',
            },
        ),
    ]
